version: "3.9"  # optional since v1.27.0
services:
  user:
    build: ./cmd/user
    ports:
      - "8001:8001"
    environment:
      PORT: 8001
    depends_on:
      - "postgres"

  notification:
    build: ./cmd/notification
    ports:
      - "8002:8002"
    environment:
      PORT: 8002
      GOOGLE_APPLICATION_CREDENTIALS: /app/credential.json
    volumes:
      - ./credential.json:/app/credential.json
    depends_on:
      - "redis"
  postgres:
      image: postgres:12.10
      restart: always
      environment:
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root
      logging:
        options:
          max-size: 10m
          max-file: "3"
      ports:
        - '5432:5432'
      volumes:
        - ./db/postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:7.0
    ports:
      - '6379:6379'
